package com.accenture.aris.inventory.business.entity;

import java.util.Date;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class StockTrackEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_track.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_track.stock_id
     *
     * @mbggenerated
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_track.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_track.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_track.operation_type
     *
     * @mbggenerated
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_track.stock_increment
     *
     * @mbggenerated
     */
    private Integer stockIncrement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_track.id
     *
     * @return the value of t_stock_track.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_track.id
     *
     * @param id the value for t_stock_track.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_track.stock_id
     *
     * @return the value of t_stock_track.stock_id
     *
     * @mbggenerated
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_track.stock_id
     *
     * @param stockId the value for t_stock_track.stock_id
     *
     * @mbggenerated
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_track.updated_by
     *
     * @return the value of t_stock_track.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_track.updated_by
     *
     * @param updatedBy the value for t_stock_track.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_track.updated_at
     *
     * @return the value of t_stock_track.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_track.updated_at
     *
     * @param updatedAt the value for t_stock_track.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_track.operation_type
     *
     * @return the value of t_stock_track.operation_type
     *
     * @mbggenerated
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_track.operation_type
     *
     * @param operationType the value for t_stock_track.operation_type
     *
     * @mbggenerated
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_track.stock_increment
     *
     * @return the value of t_stock_track.stock_increment
     *
     * @mbggenerated
     */
    public Integer getStockIncrement() {
        return stockIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_track.stock_increment
     *
     * @param stockIncrement the value for t_stock_track.stock_increment
     *
     * @mbggenerated
     */
    public void setStockIncrement(Integer stockIncrement) {
        this.stockIncrement = stockIncrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_track
     *
     * @mbggenerated Mon Oct 16 15:23:39 CST 2017
     */
    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}